return {
    "The Anubis",
    "Love and Pain",
    "We do a little trolling",
    "The Conqueror",
    "Wielder of Death",
    "Requiem",
    "Six Eyes",
    "Daily Quest",
    "Daily Quest",
    "Daily Quest",
    "Daily Quest",
    "Daily Quest",
    "Daily Quest",
    "Daily Quest",
    "Followers Exclusive!!!",
    "Road to Green Boy",
    "Colors of Life",
    "????????",
    "Only One",
    "Shadow Hunting",
    "Curses Until The End",
    "SaKUra StAnD 2077",
    "The Cyber Skeleton",
    "The Holiday Skeleton",
    "The Path to True Strength",
    "Forgotten Identity",
    "In Pursuit of Truth",
    "The Librarian's Errand",
    "The Library Invitation",
    "Suppression of The Black Silence",
    "Path of Espada",
    "Free your Soul",
    "Lilynette",
    "Primera Espada",
    "Partial Resurreccion",
    "Isolation",
    "Los Lobos",
    "Full Resurreccion",
    "Solitude",
    "Back Side of Left Hand",
    "Unlocking Ones E.G.O",
    ""The Wandering Samurai"",
    "Prove Yourself",
    ""The Man"",
    ""Lost Right Arm"",
    ""Path To Awaken"",
    "The Curse Within",
    "à¹€à¸„à¸§à¸ªà¹€à¸«à¸µà¹ˆà¸¢à¹„à¸£à¸§à¸°à¹à¸¡à¹ˆà¸‡",
    "à¸­à¸±à¸™à¸™à¸µà¹‰à¸à¹‰à¸ªà¹‰à¸™à¸•à¸µà¸™à¸­à¸°à¹„à¸£à¸­à¸µà¸",
    "Lost Souls",
    "Something Precious",
    "A Blade Written in Ink",
    "Secret of the Dark Alley",
    "Show Your Worth",
    "Heretics of the Blades",
    "Back Alley Again",
    "Five Rings",
    "The Epic of Gilgamesh",
    "Lost Carrots",
    "Community Service???",
    "The Final Stretch",
    "Auddy's problem",
    "Kuzma's problem",
    "Rebirth A New",
    "New Universe Struggle",
    "A Minor Inconvenience",
    "The First Selection",
    "The Second Selection",
    "Playing Soccer With Your Life On The Line",
    "Flow",
    "Water Training",
    "Water Stream Rock Smashing Fist",
    "Strengthen You Bond To The Order",
    "Joining The Paladinas",
    "Seeking the Paladinas",
    "Cleanse the world of #F@-E's Influence",
    "The Chaotic Slayer",
    "Seeing the Truth Within Yourself",
    "Genesis of Order",
    "Test of Faith",
    "Trial of Order",
    "Sealed Sword",
    "Big Fish Eat Little Fish",
    "Fear the Man Who Has Nothing To Lose",
    "Infinity Castle Investigation",
    "...",
    "Gather Blood",
    "Prove your worth",
    "Strength Training",
    "Magic Training",
    "Mind Training",
    "Never Give a Sword to a Man Who Can't Dance 1",
    "Never Give a Sword to a Man Who Can't Dance 2",
    "Never Give a Sword to a Man Who Can't Dance 3",
    "Never Give a Sword to a Man Who Can't Dance 4",
    "Never Give a Sword to a Man Who Can't Dance 5",
    "Never Give a Sword to a Man Who Can't Dance 6",
    "The Blade is only as Sharp as the Soul Holding It 1",
    "The Blade is only as Sharp as the Soul Holding It 2",
    "The Blade is only as Sharp as the Soul Holding It 3",
    "The Blade is only as Sharp as the Soul Holding It 4",
    "Preparing for Hueco Mundo",
    "A Feast Fit for a King",
    "Supreme Helper Minion",
    "Into the Sakura Stand",
    "A Humble Request",
    "Ashes to Ashes. Dust to Dust.",
    "Second Chance With Cupid",
    "Lost Power Source",
    "Talk to Rize",
    "Who knew evil girls have the prettiest face?",
    "Get Stronger",
    "Get Smarter",
    "May you prosper and be in good health",
    "May your hunger be satiated",
    "May your greed know no bounds",
    "May your power bring rage",
    "May your rage bring haste",
    "May you find all you have lost",
    "Corrupt your soul",
}
